// Generated by gencpp from file ibvs_pkg/xyzyawVel.msg
// DO NOT EDIT!


#ifndef IBVS_PKG_MESSAGE_XYZYAWVEL_H
#define IBVS_PKG_MESSAGE_XYZYAWVEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ibvs_pkg
{
template <class ContainerAllocator>
struct xyzyawVel_
{
  typedef xyzyawVel_<ContainerAllocator> Type;

  xyzyawVel_()
    : header()
    , Vx(0.0)
    , Vy(0.0)
    , Vz(0.0)
    , Vyaw(0.0)  {
    }
  xyzyawVel_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Vx(0.0)
    , Vy(0.0)
    , Vz(0.0)
    , Vyaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _Vx_type;
  _Vx_type Vx;

   typedef float _Vy_type;
  _Vy_type Vy;

   typedef float _Vz_type;
  _Vz_type Vz;

   typedef float _Vyaw_type;
  _Vyaw_type Vyaw;





  typedef boost::shared_ptr< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> const> ConstPtr;

}; // struct xyzyawVel_

typedef ::ibvs_pkg::xyzyawVel_<std::allocator<void> > xyzyawVel;

typedef boost::shared_ptr< ::ibvs_pkg::xyzyawVel > xyzyawVelPtr;
typedef boost::shared_ptr< ::ibvs_pkg::xyzyawVel const> xyzyawVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ibvs_pkg::xyzyawVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ibvs_pkg::xyzyawVel_<ContainerAllocator1> & lhs, const ::ibvs_pkg::xyzyawVel_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Vx == rhs.Vx &&
    lhs.Vy == rhs.Vy &&
    lhs.Vz == rhs.Vz &&
    lhs.Vyaw == rhs.Vyaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ibvs_pkg::xyzyawVel_<ContainerAllocator1> & lhs, const ::ibvs_pkg::xyzyawVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ibvs_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf984bc80b8e8684cced7bacc6b18f87";
  }

  static const char* value(const ::ibvs_pkg::xyzyawVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf984bc80b8e8684ULL;
  static const uint64_t static_value2 = 0xcced7bacc6b18f87ULL;
};

template<class ContainerAllocator>
struct DataType< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ibvs_pkg/xyzyawVel";
  }

  static const char* value(const ::ibvs_pkg::xyzyawVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32 Vx\n"
"float32 Vy\n"
"float32 Vz\n"
"float32 Vyaw\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ibvs_pkg::xyzyawVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Vx);
      stream.next(m.Vy);
      stream.next(m.Vz);
      stream.next(m.Vyaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xyzyawVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ibvs_pkg::xyzyawVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ibvs_pkg::xyzyawVel_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Vx: ";
    Printer<float>::stream(s, indent + "  ", v.Vx);
    s << indent << "Vy: ";
    Printer<float>::stream(s, indent + "  ", v.Vy);
    s << indent << "Vz: ";
    Printer<float>::stream(s, indent + "  ", v.Vz);
    s << indent << "Vyaw: ";
    Printer<float>::stream(s, indent + "  ", v.Vyaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IBVS_PKG_MESSAGE_XYZYAWVEL_H
