// Generated by gencpp from file custom_msgs/ImgRecog.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_IMGRECOG_H
#define CUSTOM_MSGS_MESSAGE_IMGRECOG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct ImgRecog_
{
  typedef ImgRecog_<ContainerAllocator> Type;

  ImgRecog_()
    : header()
    , detected_cnt(0)
    , detected_num()
    , point()  {
    }
  ImgRecog_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detected_cnt(0)
    , detected_num(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _detected_cnt_type;
  _detected_cnt_type detected_cnt;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _detected_num_type;
  _detected_num_type detected_num;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::custom_msgs::ImgRecog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ImgRecog_<ContainerAllocator> const> ConstPtr;

}; // struct ImgRecog_

typedef ::custom_msgs::ImgRecog_<std::allocator<void> > ImgRecog;

typedef boost::shared_ptr< ::custom_msgs::ImgRecog > ImgRecogPtr;
typedef boost::shared_ptr< ::custom_msgs::ImgRecog const> ImgRecogConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ImgRecog_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ImgRecog_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::ImgRecog_<ContainerAllocator1> & lhs, const ::custom_msgs::ImgRecog_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detected_cnt == rhs.detected_cnt &&
    lhs.detected_num == rhs.detected_num &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::ImgRecog_<ContainerAllocator1> & lhs, const ::custom_msgs::ImgRecog_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImgRecog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImgRecog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImgRecog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImgRecog_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImgRecog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImgRecog_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ImgRecog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cc7bc92017f3829a0d9445ce06b3944";
  }

  static const char* value(const ::custom_msgs::ImgRecog_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cc7bc92017f3829ULL;
  static const uint64_t static_value2 = 0xa0d9445ce06b3944ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ImgRecog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ImgRecog";
  }

  static const char* value(const ::custom_msgs::ImgRecog_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ImgRecog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 detected_cnt\n"
"uint8[] detected_num\n"
"\n"
"\n"
"geometry_msgs/Point[] point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msgs::ImgRecog_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ImgRecog_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detected_cnt);
      stream.next(m.detected_num);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImgRecog_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ImgRecog_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ImgRecog_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detected_cnt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected_cnt);
    s << indent << "detected_num[]" << std::endl;
    for (size_t i = 0; i < v.detected_num.size(); ++i)
    {
      s << indent << "  detected_num[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.detected_num[i]);
    }
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_IMGRECOG_H
