// Generated by gencpp from file custom_msgs/PurposeWp.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_PURPOSEWP_H
#define CUSTOM_MSGS_MESSAGE_PURPOSEWP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nav_msgs/Path.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct PurposeWp_
{
  typedef PurposeWp_<ContainerAllocator> Type;

  PurposeWp_()
    : header()
    , purpose(0)
    , path()  {
    }
  PurposeWp_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , purpose(0)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _purpose_type;
  _purpose_type purpose;

   typedef  ::nav_msgs::Path_<ContainerAllocator>  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::custom_msgs::PurposeWp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::PurposeWp_<ContainerAllocator> const> ConstPtr;

}; // struct PurposeWp_

typedef ::custom_msgs::PurposeWp_<std::allocator<void> > PurposeWp;

typedef boost::shared_ptr< ::custom_msgs::PurposeWp > PurposeWpPtr;
typedef boost::shared_ptr< ::custom_msgs::PurposeWp const> PurposeWpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::PurposeWp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::PurposeWp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::PurposeWp_<ContainerAllocator1> & lhs, const ::custom_msgs::PurposeWp_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.purpose == rhs.purpose &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::PurposeWp_<ContainerAllocator1> & lhs, const ::custom_msgs::PurposeWp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::PurposeWp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::PurposeWp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::PurposeWp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::PurposeWp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::PurposeWp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::PurposeWp_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::PurposeWp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75b00cd1cd8f634afebd0ef55df62682";
  }

  static const char* value(const ::custom_msgs::PurposeWp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75b00cd1cd8f634aULL;
  static const uint64_t static_value2 = 0xfebd0ef55df62682ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::PurposeWp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/PurposeWp";
  }

  static const char* value(const ::custom_msgs::PurposeWp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::PurposeWp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 purpose\n"
"nav_msgs/Path path\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::custom_msgs::PurposeWp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::PurposeWp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.purpose);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PurposeWp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::PurposeWp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::PurposeWp_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "purpose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.purpose);
    s << indent << "path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_PURPOSEWP_H
